modLoader="javafml"
loaderVersion="[44,)"
license="MIT license"
issueTrackerURL="https://github.com/xmlySUM/Xmly_EnchantmentsTooltip"
[[mods]]
modId="xmlyenchantip"
version="1.0.2"
displayName="Xmly's Enchantments Tooltip"
authors="xmlySUM"
description='''make a tooltip for enchantments'''
displayURL="https://www.curseforge.com/minecraft/mc-mods/xmly-enchantmentstooltip"
logoFile= "icon.png"

[[dependencies.xmlyenchantip]]
modId="minecraft"
mandatory=true
versionRange="[1.20,)"
ordering="NONE"
side="BOTH"